# Конфигурация Telegram бота без хардкода
telegram_bot:
  # Токен бота загружается из переменной окружения
  # Установите: export TELEGRAM_BOT_TOKEN="8181686852:AAH93K4NhfI2oUhhrvLd9MK8Eln1_XsyFi4"
  token_env_var: "TELEGRAM_BOT_TOKEN"
  
  # Настройки соединения
  timeout: 30
  connection_pool_size: 8
  
  # Безопасность
  allowed_users: []  # Пустой список означает "все пользователи"
  admin_users_env_var: "BOT_ADMIN_USERS"  # JSON массив user_id
  max_message_length: 4096
  rate_limit:
    messages_per_minute: 20
    commands_per_hour: 100
  
  # Функциональность
  commands:
    start:
      description: "Запуск бота и приветствие"
      enabled: true
    help:
      description: "Справка по командам"
      enabled: true
    status:
      description: "Статус системы памяти"
      enabled: true
    config:
      description: "Текущая конфигурация (только для админов)"
      enabled: true
      admin_only: true
    test_memory:
      description: "Тест системы памяти"
      enabled: true
    test_search:
      description: "Тест поиска в памяти"
      enabled: true
    metrics:
      description: "Метрики системы"
      enabled: true
      admin_only: true
  
  # Интеграция с системой памяти
  memory_integration:
    store_conversations: true
    user_prefix: "telegram_user_"
    default_language: "ru"
    importance_boost: 0.1  # Бонус важности для сообщений из Telegram
    
  # Ответы и сообщения
  messages:
    welcome: |
      🤖 Привет! Я бот для тестирования системы памяти Agata.
      
      Доступные команды:
      /help - справка
      /status - статус системы
      /test_memory - тест памяти
      /test_search - тест поиска
      
      Просто напишите мне что-нибудь, и я сохраню это в памяти!
    
    help: |
      📖 Справка по командам:
      
      /start - перезапуск и приветствие
      /status - проверка состояния системы памяти
      /test_memory <текст> - сохранить текст в память
      /test_search <запрос> - найти в памяти
      /metrics - метрики системы (админы)
      /config - конфигурация (админы)
      
      Все обычные сообщения автоматически сохраняются в память.
    
    unauthorized: "⛔ У вас нет доступа к этой команде"
    error_generic: "❌ Произошла ошибка: {error}"
    memory_saved: "✅ Сохранено в память"
    memory_error: "❌ Ошибка сохранения: {error}"
    search_no_results: "🔍 Ничего не найдено по запросу: {query}"
    
  # Логирование
  logging:
    level: "INFO"
    format: "[%(asctime)s] %(name)s [%(levelname)s] %(message)s"
    log_chat_messages: false  # Не логируем содержимое сообщений для приватности
    log_commands: true
    log_errors: true
