# Конфигурация для EnhancedBufferMemory
# Никакого хардкода в коде - все настройки здесь

# Настройки эмоций
emotion_markers:
  happy:
    - "спасибо"
    - "отлично" 
    - "прекрасно"
    - "радость"
    - "😊"
    - "👍"
    - "круто"
    - "замечательно"
    - "класс"
    - "супер"
  
  excited:
    - "ура"
    - "супер"
    - "классно"
    - "восторг"
    - "🎉"
    - "восхитительно"
    - "потрясающе"
    - "офигенно"
  
  grateful:
    - "благодарен"
    - "признателен"
    - "спасибо большое"
    - "очень благодарен"
    - "сердечно благодарю"
  
  sad:
    - "грустно"
    - "печально"
    - "расстроен"
    - "😢"
    - "😭"
    - "плохо"
    - "тоскливо"
    - "депрессия"
  
  worried:
    - "беспокоюсь"
    - "волнуюсь"
    - "переживаю"
    - "😰"
    - "тревожно"
    - "страшно"
    - "нервничаю"
  
  confused:
    - "не понимаю"
    - "запутался"
    - "непонятно"
    - "🤔"
    - "странно"
    - "сложно"
    - "сбивает с толку"
  
  frustrated:
    - "раздражает"
    - "злит"
    - "бесит"
    - "достало"
    - "😠"
    - "ненавижу"
    - "выводит из себя"
    - "надоело"

# Настройки расчета важности
importance_calculation:
  # Веса по ролям
  role_weights:
    user: 0.7
    assistant: 0.5
    system: 0.3
  
  # Маркеры важности
  importance_markers:
    critical:
      markers:
        - "важно"
        - "срочно"
        - "критично"
        - "обязательно"
        - "необходимо"
      weight: 0.3
    
    help_request:
      markers:
        - "помогите"
        - "помоги"
        - "проблема"
        - "ошибка"
        - "не работает"
        - "сломалось"
      weight: 0.2
    
    personal_info:
      markers:
        - "меня зовут"
        - "мое имя"
        - "я работаю"
        - "живу в"
        - "мне лет"
        - "моя профессия"
        - "мой возраст"
      weight: 0.25
    
    low_importance:
      markers:
        - "привет"
        - "пока"
        - "спасибо"
        - "да"
        - "нет"
        - "ок"
        - "хорошо"
      weight: -0.2
  
  # Настройки длины сообщений
  length_weights:
    long_threshold: 200
    short_threshold: 10
    long_bonus: 0.1
    short_penalty: -0.1

# Ключевые слова для тем
topic_keywords:
  работа:
    - "работ"
    - "профессия"
    - "карьер"
    - "офис"
    - "компания"
    - "начальник"
    - "коллега"
    - "зарплата"
    - "проект"
  
  семья:
    - "семья"
    - "родители"
    - "дети"
    - "муж"
    - "жена"
    - "сын"
    - "дочь"
    - "мама"
    - "папа"
  
  хобби:
    - "увлекаюсь"
    - "люблю"
    - "хобби"
    - "интерес"
    - "занимаюсь"
    - "коллекционирую"
    - "играю"
    - "читаю"
  
  здоровье:
    - "здоровье"
    - "самочувствие"
    - "болезнь"
    - "врач"
    - "лечение"
    - "таблетки"
    - "больница"
    - "симптомы"
  
  путешествия:
    - "путешеств"
    - "отпуск"
    - "страна"
    - "город"
    - "поездка"
    - "отдых"
    - "туризм"
    - "экскурсия"
  
  образование:
    - "учусь"
    - "университет"
    - "школа"
    - "курс"
    - "экзамен"
    - "диплом"
    - "лекция"
    - "студент"
  
  технологии:
    - "компьютер"
    - "программирование"
    - "код"
    - "сайт"
    - "приложение"
    - "интернет"
    - "программа"
    - "разработка"
  
  спорт:
    - "спорт"
    - "тренировка"
    - "фитнес"
    - "бег"
    - "зал"
    - "футбол"
    - "теннис"
    - "плавание"

# Настройки LLM для суммаризации
llm:
  summarization_model: "gpt-4o-mini"
  summarization_temperature: 0.3
  max_tokens_summary: 500

# Включение/выключение функций
features:
  auto_summarization: true
  emotion_detection: true
  behavior_adaptation: true
  context_enrichment: true
