# Конфигурация живого общения
living_chat:
  # Настройки разбиения сообщений
  message_splitting:
    max_length: 200  # Увеличиваем для более естественных сообщений
    force_split_threshold: 300  # Разбиваем только очень длинные сообщения
    min_delay_ms: 1500  # 1.5 секунды
    max_delay_ms: 5500  # 3.5 секунды  
    max_parts: 2  # Максимум 2 части для естественности
  
  # Настройки коротких сообщений
  short_messages:
    max_wait_seconds: 10  # Уменьшаем время ожидания
    short_message_threshold: 50  # символов
    quick_sequence_threshold: 3  # секунд между сообщениями (быстрее объединение)
    

  # Динамічна генерація замість хардкоду
  dynamic_generation:
    enabled: true
    use_openai_for_questions: true
    use_openai_for_emotions: true
    use_openai_for_connectors: true
    cache_duration_minutes: 30
    
  # Базові часові діапазони
  time_ranges:
    morning: [6, 12]
    day: [12, 18]
    evening: [18, 22]
    night: [22, 6]
  
  # Стиль общения
  communication_style:
    use_emojis: true 
    use_parentheses: false  
    use_contractions: true 
    max_emoji_per_message: 1
    emoji_frequency: 0.3  # 30% сообщений с эмодзи (не все)
    casual_expressions: true
