# Конфигурация живого общения (БЕЗ ХАРДКОДУ)
living_chat:
  # Настройки разбиения сообщений
  message_splitting:
    max_length: 250  # Збільшуємо для повних думок
    force_split_threshold: 180  # Поріг для природного розподілу
    min_delay_ms: 5000  # 3 секунди - як людина думає
    max_delay_ms: 8000  # 8 секунд - довші паузи для природності
    max_parts: 2  # Максимум 2 части для більш цілісних повідомлень
  
  # Настройки коротких сообщений
  short_messages:
    max_wait_seconds: 10  # Уменьшаем время ожидания
    short_message_threshold: 50  # символов
    quick_sequence_threshold: 3  # секунд между сообщениями (быстрее объединение)
    

  dynamic_generation:
    enabled: true
    use_openai_for_questions: true
    use_openai_for_emotions: true
    use_openai_for_connectors: true
    cache_duration_minutes: 30  # Кешуємо згенерований контент
    
  # Базові часові діапазони (статичні)
  time_ranges:
    morning: [6, 12]
    day: [12, 18]
    evening: [18, 22]
    night: [22, 6]
  
  # Стиль общения
  communication_style:
    use_emojis: true 
    use_parentheses: false  
    use_contractions: true 
    max_emoji_per_message: 1
    casual_expressions: true
