# Конфигурация для MemoryAdapter
memory_adapter:
  # Максимальное количество фактов для долгосрочной памяти
  # Уменьшаем для лучшей производительности при большом количестве сообщений
  max_facts: 20
  
  # Максимальное количество сообщений для краткосрочной памяти
  # Оптимизируем для быстрой работы
  max_short_messages: 15
  
  # Максимальное количество результатов для семантического поиска
  # Уменьшаем для снижения нагрузки
  max_semantic_results: 5
  
  # Множитель для поиска фактов (во сколько раз больше результатов искать для фактов)
  # Снижаем для оптимизации
  facts_search_multiplier: 2
  
  # Настройки обработки контента
  content_limits:
    # Максимальная длина сообщения для отображения в кратком виде
    short_message_length: 100
    # Минимальная длина факта для включения в результат
    min_fact_length: 10
    # Минимальная длина документа для включения в контекст
    min_document_length: 3
    # Длина превью для логов
    log_preview_length: 50
    # Длина превью для фактов в логах
    fact_log_preview_length: 30
  
  # Поисковые запросы для разных типов информации
  search_queries:
    personal_info: "личная информация пользователь предпочтения интересы семья работа учеба"
    general_context: "контекст диалог разговор общение"
  
  # Ключевые слова для определения личной информации
  personal_keywords:
    - 'зовут'
    - 'имя'
    - 'меня'
    - 'лет'
    - 'возраст'
    - 'работа'
    - 'профессия'
    - 'живу'
    - 'город'
    - 'страна'
    - 'семья'
    - 'родители'
    - 'мама'
    - 'папа'
    - 'люблю'
    - 'нравится'
    - 'предпочитаю'
    - 'делаю'
    - 'занимаюсь'
    - 'учусь'
    - 'хобби'
    - 'увлечения'
    - 'интересы'
    - 'цели'
    - 'планы'
    - 'мечты'